/**
 * Catálogo CANÓNICO de idiomas de OmniVoice — los 646 que soporta el modelo.
 * Generado desde omnivoice/utils/lang_map.py. NADA afuera.
 *
 * Los primeros son los más usados (con label nativo + bandera); el resto sigue
 * el nombre canónico en inglés de OmniVoice. El `code` es el ISO 639 que el
 * modelo entiende; `name` es el nombre exacto que también acepta `language`.
 */
export interface Language {
  code: string;
  label: string;
  flag: string;
  /** Nombre canónico en inglés (lo que OmniVoice usa internamente). */
  canonical?: string;
}

export const LANGUAGES: Language[] = [
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱" },
  { code: "pl", label: "Polski", flag: "🇵🇱" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "uk", label: "Українська", flag: "🇺🇦" },
  { code: "tr", label: "Türkçe", flag: "🇹🇷" },
  { code: "ja", label: "日本語", flag: "🇯🇵" },
  { code: "ko", label: "한국어", flag: "🇰🇷" },
  { code: "zh", label: "中文 (Mandarín)", flag: "🇨🇳" },
  { code: "yue", label: "粵語 (Cantonés)", flag: "🇭🇰" },
  { code: "arb", label: "العربية (estándar)", flag: "🇸🇦" },
  { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", label: "বাংলা", flag: "🇧🇩" },
  { code: "ta", label: "தமிழ்", flag: "🇮🇳" },
  { code: "te", label: "తెలుగు", flag: "🇮🇳" },
  { code: "ml", label: "മലയാളം", flag: "🇮🇳" },
  { code: "kn", label: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "mr", label: "मराठी", flag: "🇮🇳" },
  { code: "gu", label: "ગુજરાતી", flag: "🇮🇳" },
  { code: "pa", label: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "ur", label: "اردو", flag: "🇵🇰" },
  { code: "id", label: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", label: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "vi", label: "Tiếng Việt", flag: "🇻🇳" },
  { code: "th", label: "ไทย", flag: "🇹🇭" },
  { code: "fil", label: "Filipino", flag: "🇵🇭" },
  { code: "my", label: "မြန်မာ", flag: "🇲🇲" },
  { code: "km", label: "ខ្មែរ", flag: "🇰🇭" },
  { code: "lo", label: "ລາວ", flag: "🇱🇦" },
  { code: "sw", label: "Kiswahili", flag: "🇰🇪" },
  { code: "yo", label: "Yorùbá", flag: "🇳🇬" },
  { code: "ha", label: "Hausa", flag: "🇳🇬" },
  { code: "ig", label: "Igbo", flag: "🇳🇬" },
  { code: "am", label: "አማርኛ", flag: "🇪🇹" },
  { code: "zu", label: "isiZulu", flag: "🇿🇦" },
  { code: "xh", label: "isiXhosa", flag: "🇿🇦" },
  { code: "so", label: "Soomaali", flag: "🇸🇴" },
  { code: "el", label: "Ελληνικά", flag: "🇬🇷" },
  { code: "he", label: "עברית", flag: "🇮🇱" },
  { code: "fa", label: "فارسی", flag: "🇮🇷" },
  { code: "cs", label: "Čeština", flag: "🇨🇿" },
  { code: "sk", label: "Slovenčina", flag: "🇸🇰" },
  { code: "hu", label: "Magyar", flag: "🇭🇺" },
  { code: "ro", label: "Română", flag: "🇷🇴" },
  { code: "bg", label: "Български", flag: "🇧🇬" },
  { code: "sv", label: "Svenska", flag: "🇸🇪" },
  { code: "no", label: "Norsk", flag: "🇳🇴" },
  { code: "da", label: "Dansk", flag: "🇩🇰" },
  { code: "fi", label: "Suomi", flag: "🇫🇮" },
  { code: "is", label: "Íslenska", flag: "🇮🇸" },
  { code: "ga", label: "Gaeilge", flag: "🇮🇪" },
  { code: "cy", label: "Cymraeg", flag: "🏴" },
  { code: "ca", label: "Català", flag: "🇪🇸" },
  { code: "gl", label: "Galego", flag: "🇪🇸" },
  { code: "eu", label: "Euskara", flag: "🇪🇸" },
  { code: "hr", label: "Hrvatski", flag: "🇭🇷" },
  { code: "sr", label: "Српски", flag: "🇷🇸" },
  { code: "sl", label: "Slovenščina", flag: "🇸🇮" },
  { code: "lt", label: "Lietuvių", flag: "🇱🇹" },
  { code: "lv", label: "Latviešu", flag: "🇱🇻" },
  { code: "et", label: "Eesti", flag: "🇪🇪" },
  { code: "mk", label: "Македонски", flag: "🇲🇰" },
  { code: "sq", label: "Shqip", flag: "🇦🇱" },
  { code: "ka", label: "ქართული", flag: "🇬🇪" },
  { code: "hy", label: "Հայերեն", flag: "🇦🇲" },
  { code: "az", label: "Azərbaycan", flag: "🇦🇿" },
  { code: "kk", label: "Қазақ", flag: "🇰🇿" },
  { code: "uz", label: "Oʻzbek", flag: "🇺🇿" },
  { code: "mn", label: "Монгол", flag: "🇲🇳" },
  { code: "si", label: "සිංහල", flag: "🇱🇰" },
  { code: "af", label: "Afrikaans", flag: "🇿🇦" },

  // ─── Resto del catálogo canónico (nombre en inglés de OmniVoice) ───
  { code: "kbt", label: "Abadi", flag: "🌐", canonical: "abadi" },
  { code: "ab", label: "Abkhazian", flag: "🌐", canonical: "abkhazian" },
  { code: "abr", label: "Abron", flag: "🌐", canonical: "abron" },
  { code: "abn", label: "Abua", flag: "🌐", canonical: "abua" },
  { code: "fub", label: "Adamawa Fulfulde", flag: "🌐", canonical: "adamawa fulfulde" },
  { code: "ady", label: "Adyghe", flag: "🌐", canonical: "adyghe" },
  { code: "aal", label: "Afade", flag: "🌐", canonical: "afade" },
  { code: "yay", label: "Agwagwune", flag: "🌐", canonical: "agwagwune" },
  { code: "ajg", label: "Aja (Benin)", flag: "🌐", canonical: "aja (benin)" },
  { code: "keu", label: "Akebu", flag: "🌐", canonical: "akebu" },
  { code: "ala", label: "Alago", flag: "🌐", canonical: "alago" },
  { code: "arq", label: "Algerian Arabic", flag: "🌐", canonical: "algerian arabic" },
  { code: "aao", label: "Algerian Saharan Arabic", flag: "🌐", canonical: "algerian saharan arabic" },
  { code: "qva", label: "Ambo-Pasco Quechua", flag: "🌐", canonical: "ambo-pasco quechua" },
  { code: "abs", label: "Ambonese Malay", flag: "🌐", canonical: "ambonese malay" },
  { code: "adx", label: "Amdo Tibetan", flag: "🌐", canonical: "amdo tibetan" },
  { code: "anw", label: "Anaang", flag: "🌐", canonical: "anaang" },
  { code: "anp", label: "Angika", flag: "🌐", canonical: "angika" },
  { code: "xmv", label: "Antankarana Malagasy", flag: "🌐", canonical: "antankarana malagasy" },
  { code: "an", label: "Aragonese", flag: "🌐", canonical: "aragonese" },
  { code: "aae", label: "Arbëreshë Albanian", flag: "🌐", canonical: "arbëreshë albanian" },
  { code: "qxu", label: "Arequipa-La Unión Quechua", flag: "🌐", canonical: "arequipa-la unión quechua" },
  { code: "ahs", label: "Ashe", flag: "🌐", canonical: "ashe" },
  { code: "prq", label: "Ashéninka Perené", flag: "🌐", canonical: "ashéninka perené" },
  { code: "eiv", label: "Askopan", flag: "🌐", canonical: "askopan" },
  { code: "as", label: "Assamese", flag: "🌐", canonical: "assamese" },
  { code: "ast", label: "Asturian", flag: "🌐", canonical: "asturian" },
  { code: "tay", label: "Atayal", flag: "🌐", canonical: "atayal" },
  { code: "awo", label: "Awak", flag: "🌐", canonical: "awak" },
  { code: "quy", label: "Ayacucho Quechua", flag: "🌐", canonical: "ayacucho quechua" },
  { code: "bba", label: "Baatonum", flag: "🌐", canonical: "baatonum" },
  { code: "bcy", label: "Bacama", flag: "🌐", canonical: "bacama" },
  { code: "bde", label: "Bade", flag: "🌐", canonical: "bade" },
  { code: "ksf", label: "Bafia", flag: "🌐", canonical: "bafia" },
  { code: "bfd", label: "Bafut", flag: "🌐", canonical: "bafut" },
  { code: "fui", label: "Bagirmi Fulfulde", flag: "🌐", canonical: "bagirmi fulfulde" },
  { code: "bqg", label: "Bago-Kusuntu", flag: "🌐", canonical: "bago-kusuntu" },
  { code: "abv", label: "Baharna Arabic", flag: "🌐", canonical: "baharna arabic" },
  { code: "bkh", label: "Bakoko", flag: "🌐", canonical: "bakoko" },
  { code: "bjt", label: "Balanta-Ganja", flag: "🌐", canonical: "balanta-ganja" },
  { code: "bft", label: "Balti", flag: "🌐", canonical: "balti" },
  { code: "bce", label: "Bamenyam", flag: "🌐", canonical: "bamenyam" },
  { code: "bax", label: "Bamun", flag: "🌐", canonical: "bamun" },
  { code: "bsj", label: "Bangwinji", flag: "🌐", canonical: "bangwinji" },
  { code: "bjn", label: "Banjar", flag: "🌐", canonical: "banjar" },
  { code: "abb", label: "Bankon", flag: "🌐", canonical: "bankon" },
  { code: "bci", label: "Baoulé", flag: "🌐", canonical: "baoulé" },
  { code: "bhr", label: "Bara Malagasy", flag: "🌐", canonical: "bara malagasy" },
  { code: "bjk", label: "Barok", flag: "🌐", canonical: "barok" },
  { code: "bas", label: "Basa (Cameroon)", flag: "🌐", canonical: "basa (cameroon)" },
  { code: "bzw", label: "Basa (Nigeria)", flag: "🌐", canonical: "basa (nigeria)" },
  { code: "ba", label: "Bashkir", flag: "🌐", canonical: "bashkir" },
  { code: "btm", label: "Batak Mandailing", flag: "🌐", canonical: "batak mandailing" },
  { code: "bnm", label: "Batanga", flag: "🌐", canonical: "batanga" },
  { code: "btv", label: "Bateri", flag: "🌐", canonical: "bateri" },
  { code: "bbl", label: "Bats", flag: "🌐", canonical: "bats" },
  { code: "bda", label: "Bayot", flag: "🌐", canonical: "bayot" },
  { code: "beb", label: "Bebele", flag: "🌐", canonical: "bebele" },
  { code: "be", label: "Belarusian", flag: "🌐", canonical: "belarusian" },
  { code: "bew", label: "Betawi", flag: "🌐", canonical: "betawi" },
  { code: "bhb", label: "Bhili", flag: "🌐", canonical: "bhili" },
  { code: "bho", label: "Bhojpuri", flag: "🌐", canonical: "bhojpuri" },
  { code: "bxf", label: "Bilur", flag: "🌐", canonical: "bilur" },
  { code: "bhp", label: "Bima", flag: "🌐", canonical: "bima" },
  { code: "brx", label: "Bodo", flag: "🌐", canonical: "bodo" },
  { code: "bux", label: "Boghom", flag: "🌐", canonical: "boghom" },
  { code: "bky", label: "Bokyi", flag: "🌐", canonical: "bokyi" },
  { code: "bmq", label: "Bomu", flag: "🌐", canonical: "bomu" },
  { code: "bou", label: "Bondei", flag: "🌐", canonical: "bondei" },
  { code: "fue", label: "Borgu Fulfulde", flag: "🌐", canonical: "borgu fulfulde" },
  { code: "bs", label: "Bosnian", flag: "🌐", canonical: "bosnian" },
  { code: "brh", label: "Brahui", flag: "🌐", canonical: "brahui" },
  { code: "bra", label: "Braj", flag: "🌐", canonical: "braj" },
  { code: "br", label: "Breton", flag: "🌐", canonical: "breton" },
  { code: "bdm", label: "Buduma", flag: "🌐", canonical: "buduma" },
  { code: "bug", label: "Buginese", flag: "🌐", canonical: "buginese" },
  { code: "bhh", label: "Bukharic", flag: "🌐", canonical: "bukharic" },
  { code: "bum", label: "Bulu (Cameroon)", flag: "🌐", canonical: "bulu (cameroon)" },
  { code: "bns", label: "Bundeli", flag: "🌐", canonical: "bundeli" },
  { code: "bnn", label: "Bunun", flag: "🌐", canonical: "bunun" },
  { code: "bwr", label: "Bura-Pabir", flag: "🌐", canonical: "bura-pabir" },
  { code: "bys", label: "Burak", flag: "🌐", canonical: "burak" },
  { code: "bsk", label: "Burushaski", flag: "🌐", canonical: "burushaski" },
  { code: "miu", label: "Cacaloxtepec Mixtec", flag: "🌐", canonical: "cacaloxtepec mixtec" },
  { code: "qvl", label: "Cajatambo North Lima Quechua", flag: "🌐", canonical: "cajatambo north lima quechua" },
  { code: "cky", label: "Cakfem-Mushere", flag: "🌐", canonical: "cakfem-mushere" },
  { code: "wes", label: "Cameroon Pidgin", flag: "🌐", canonical: "cameroon pidgin" },
  { code: "sro", label: "Campidanese Sardinian", flag: "🌐", canonical: "campidanese sardinian" },
  { code: "ceb", label: "Cebuano", flag: "🌐", canonical: "cebuano" },
  { code: "cen", label: "Cen", flag: "🌐", canonical: "cen" },
  { code: "ckb", label: "Central Kurdish", flag: "🌐", canonical: "central kurdish" },
  { code: "nhn", label: "Central Nahuatl", flag: "🌐", canonical: "central nahuatl" },
  { code: "pbs", label: "Central Pame", flag: "🌐", canonical: "central pame" },
  { code: "pst", label: "Central Pashto", flag: "🌐", canonical: "central pashto" },
  { code: "ncx", label: "Central Puebla Nahuatl", flag: "🌐", canonical: "central puebla nahuatl" },
  { code: "tar", label: "Central Tarahumara", flag: "🌐", canonical: "central tarahumara" },
  { code: "esu", label: "Central Yupik", flag: "🌐", canonical: "central yupik" },
  { code: "fuq", label: "Central-Eastern Niger Fulfulde", flag: "🌐", canonical: "central-eastern niger fulfulde" },
  { code: "shu", label: "Chadian Arabic", flag: "🌐", canonical: "chadian arabic" },
  { code: "ny", label: "Chichewa", flag: "🌐", canonical: "chichewa" },
  { code: "zpv", label: "Chichicapan Zapotec", flag: "🌐", canonical: "chichicapan zapotec" },
  { code: "cgg", label: "Chiga", flag: "🌐", canonical: "chiga" },
  { code: "zoh", label: "Chimalapa Zoque", flag: "🌐", canonical: "chimalapa zoque" },
  { code: "qug", label: "Chimborazo Highland Quichua", flag: "🌐", canonical: "chimborazo highland quichua" },
  { code: "qxa", label: "Chiquián Ancash Quechua", flag: "🌐", canonical: "chiquián ancash quechua" },
  { code: "the", label: "Chitwania Tharu", flag: "🌐", canonical: "chitwania tharu" },
  { code: "cjk", label: "Chokwe", flag: "🌐", canonical: "chokwe" },
  { code: "cv", label: "Chuvash", flag: "🌐", canonical: "chuvash" },
  { code: "ckl", label: "Cibak", flag: "🌐", canonical: "cibak" },
  { code: "kjc", label: "Coastal Konjo", flag: "🌐", canonical: "coastal konjo" },
  { code: "zoc", label: "Copainalá Zoque", flag: "🌐", canonical: "copainalá zoque" },
  { code: "kw", label: "Cornish", flag: "🌐", canonical: "cornish" },
  { code: "qwa", label: "Corongo Ancash Quechua", flag: "🌐", canonical: "corongo ancash quechua" },
  { code: "mfn", label: "Cross River Mbembe", flag: "🌐", canonical: "cross river mbembe" },
  { code: "xtu", label: "Cuyamecalco Mixtec", flag: "🌐", canonical: "cuyamecalco mixtec" },
  { code: "dbd", label: "Dadiya", flag: "🌐", canonical: "dadiya" },
  { code: "dag", label: "Dagbani", flag: "🌐", canonical: "dagbani" },
  { code: "dml", label: "Dameli", flag: "🌐", canonical: "dameli" },
  { code: "dar", label: "Dargwa", flag: "🌐", canonical: "dargwa" },
  { code: "dzg", label: "Dazaga", flag: "🌐", canonical: "dazaga" },
  { code: "dcc", label: "Deccan", flag: "🌐", canonical: "deccan" },
  { code: "deg", label: "Degema", flag: "🌐", canonical: "degema" },
  { code: "kna", label: "Dera (Nigeria)", flag: "🌐", canonical: "dera (nigeria)" },
  { code: "dgh", label: "Dghwede", flag: "🌐", canonical: "dghwede" },
  { code: "mki", label: "Dhatki", flag: "🌐", canonical: "dhatki" },
  { code: "dv", label: "Dhivehi", flag: "🌐", canonical: "dhivehi" },
  { code: "adf", label: "Dhofari Arabic", flag: "🌐", canonical: "dhofari arabic" },
  { code: "cfa", label: "Dijim-Bwilim", flag: "🌐", canonical: "dijim-bwilim" },
  { code: "dgo", label: "Dogri", flag: "🌐", canonical: "dogri" },
  { code: "dmk", label: "Domaaki", flag: "🌐", canonical: "domaaki" },
  { code: "dty", label: "Dotyali", flag: "🌐", canonical: "dotyali" },
  { code: "dua", label: "Duala", flag: "🌐", canonical: "duala" },
  { code: "ldb", label: "DũYa", flag: "🌐", canonical: "dũya" },
  { code: "dyu", label: "Dyula", flag: "🌐", canonical: "dyula" },
  { code: "bgp", label: "Eastern Balochi", flag: "🌐", canonical: "eastern balochi" },
  { code: "gui", label: "Eastern Bolivian Guaraní", flag: "🌐", canonical: "eastern bolivian guaraní" },
  { code: "avl", label: "Eastern Egyptian Bedawi Arabic", flag: "🌐", canonical: "eastern egyptian bedawi arabic" },
  { code: "kqo", label: "Eastern Krahn", flag: "🌐", canonical: "eastern krahn" },
  { code: "mhr", label: "Eastern Mari", flag: "🌐", canonical: "eastern mari" },
  { code: "ydd", label: "Eastern Yiddish", flag: "🌐", canonical: "eastern yiddish" },
  { code: "ebr", label: "Ebrié", flag: "🌐", canonical: "ebrié" },
  { code: "ego", label: "Eggon", flag: "🌐", canonical: "eggon" },
  { code: "arz", label: "Egyptian Arabic", flag: "🌐", canonical: "egyptian arabic" },
  { code: "etu", label: "Ejagham", flag: "🌐", canonical: "ejagham" },
  { code: "elm", label: "Eleme", flag: "🌐", canonical: "eleme" },
  { code: "afo", label: "Eloyi", flag: "🌐", canonical: "eloyi" },
  { code: "ebu", label: "Embu", flag: "🌐", canonical: "embu" },
  { code: "myv", label: "Erzya", flag: "🌐", canonical: "erzya" },
  { code: "ish", label: "Esan", flag: "🌐", canonical: "esan" },
  { code: "eo", label: "Esperanto", flag: "🌐", canonical: "esperanto" },
  { code: "eto", label: "Eton (Cameroon)", flag: "🌐", canonical: "eton (cameroon)" },
  { code: "ewo", label: "Ewondo", flag: "🌐", canonical: "ewondo" },
  { code: "ext", label: "Extremaduran", flag: "🌐", canonical: "extremaduran" },
  { code: "fan", label: "Fang (Equatorial Guinea)", flag: "🌐", canonical: "fang (equatorial guinea)" },
  { code: "fat", label: "Fanti", flag: "🌐", canonical: "fanti" },
  { code: "gur", label: "Farefare", flag: "🌐", canonical: "farefare" },
  { code: "fmp", label: "Fe'fe'", flag: "🌐", canonical: "fe'fe'" },
  { code: "tlp", label: "Filomena Mata-Coahuitlán Totonac", flag: "🌐", canonical: "filomena mata-coahuitlán totonac" },
  { code: "fip", label: "Fipa", flag: "🌐", canonical: "fipa" },
  { code: "ff", label: "Fulah", flag: "🌐", canonical: "fulah" },
  { code: "wof", label: "Gambian Wolof", flag: "🌐", canonical: "gambian wolof" },
  { code: "lg", label: "Ganda", flag: "🌐", canonical: "ganda" },
  { code: "gbm", label: "Garhwali", flag: "🌐", canonical: "garhwali" },
  { code: "gwt", label: "Gawar-Bati", flag: "🌐", canonical: "gawar-bati" },
  { code: "gwc", label: "Gawri", flag: "🌐", canonical: "gawri" },
  { code: "gbr", label: "Gbagyi", flag: "🌐", canonical: "gbagyi" },
  { code: "gby", label: "Gbari", flag: "🌐", canonical: "gbari" },
  { code: "gyz", label: "Geji", flag: "🌐", canonical: "geji" },
  { code: "gej", label: "Gen", flag: "🌐", canonical: "gen" },
  { code: "ges", label: "Geser-Gorom", flag: "🌐", canonical: "geser-gorom" },
  { code: "aln", label: "Gheg Albanian", flag: "🌐", canonical: "gheg albanian" },
  { code: "bbj", label: "Ghomálá'", flag: "🌐", canonical: "ghomálá'" },
  { code: "gid", label: "Gidar", flag: "🌐", canonical: "gidar" },
  { code: "glw", label: "Glavda", flag: "🌐", canonical: "glavda" },
  { code: "gom", label: "Goan Konkani", flag: "🌐", canonical: "goan konkani" },
  { code: "gig", label: "Goaria", flag: "🌐", canonical: "goaria" },
  { code: "ank", label: "Goemai", flag: "🌐", canonical: "goemai" },
  { code: "gol", label: "Gola", flag: "🌐", canonical: "gola" },
  { code: "gn", label: "Guarani", flag: "🌐", canonical: "guarani" },
  { code: "gdf", label: "Guduf-Gava", flag: "🌐", canonical: "guduf-gava" },
  { code: "amu", label: "Guerrero Amuzgo", flag: "🌐", canonical: "guerrero amuzgo" },
  { code: "gju", label: "Gujari", flag: "🌐", canonical: "gujari" },
  { code: "afb", label: "Gulf Arabic", flag: "🌐", canonical: "gulf arabic" },
  { code: "ggg", label: "Gurgula", flag: "🌐", canonical: "gurgula" },
  { code: "guz", label: "Gusii", flag: "🌐", canonical: "gusii" },
  { code: "gsl", label: "Gusilay", flag: "🌐", canonical: "gusilay" },
  { code: "gwe", label: "Gweno", flag: "🌐", canonical: "gweno" },
  { code: "ztu", label: "Güilá Zapotec", flag: "🌐", canonical: "güilá zapotec" },
  { code: "hoj", label: "Hadothi", flag: "🌐", canonical: "hadothi" },
  { code: "hah", label: "Hahon", flag: "🌐", canonical: "hahon" },
  { code: "ht", label: "Haitian", flag: "🌐", canonical: "haitian" },
  { code: "cnh", label: "Hakha Chin", flag: "🌐", canonical: "hakha chin" },
  { code: "hao", label: "Hakö", flag: "🌐", canonical: "hakö" },
  { code: "hla", label: "Halia", flag: "🌐", canonical: "halia" },
  { code: "haw", label: "Hawaiian", flag: "🌐", canonical: "hawaiian" },
  { code: "haz", label: "Hazaragi", flag: "🌐", canonical: "hazaragi" },
  { code: "hem", label: "Hemba", flag: "🌐", canonical: "hemba" },
  { code: "hz", label: "Herero", flag: "🌐", canonical: "herero" },
  { code: "kjk", label: "Highland Konjo", flag: "🌐", canonical: "highland konjo" },
  { code: "acw", label: "Hijazi Arabic", flag: "🌐", canonical: "hijazi arabic" },
  { code: "var", label: "Huarijio", flag: "🌐", canonical: "huarijio" },
  { code: "mau", label: "Huautla Mazatec", flag: "🌐", canonical: "huautla mazatec" },
  { code: "nhq", label: "Huaxcaleca Nahuatl", flag: "🌐", canonical: "huaxcaleca nahuatl" },
  { code: "hbb", label: "Huba", flag: "🌐", canonical: "huba" },
  { code: "mxs", label: "Huitepec Mixtec", flag: "🌐", canonical: "huitepec mixtec" },
  { code: "hul", label: "Hula", flag: "🌐", canonical: "hula" },
  { code: "hkk", label: "Hunjara-Kaina Ke", flag: "🌐", canonical: "hunjara-kaina ke" },
  { code: "hwo", label: "Hwana", flag: "🌐", canonical: "hwana" },
  { code: "ibb", label: "Ibibio", flag: "🌐", canonical: "ibibio" },
  { code: "ida", label: "Idakho-Isukha-Tiriki", flag: "🌐", canonical: "idakho-isukha-tiriki" },
  { code: "idu", label: "Idoma", flag: "🌐", canonical: "idoma" },
  { code: "ahl", label: "Igo", flag: "🌐", canonical: "igo" },
  { code: "kpo", label: "Ikposo", flag: "🌐", canonical: "ikposo" },
  { code: "ikw", label: "Ikwere", flag: "🌐", canonical: "ikwere" },
  { code: "qvi", label: "Imbabura Highland Quichua", flag: "🌐", canonical: "imbabura highland quichua" },
  { code: "mvy", label: "Indus Kohistani", flag: "🌐", canonical: "indus kohistani" },
  { code: "ia", label: "Interlingua (International Auxiliary Language Association)", flag: "🌐", canonical: "interlingua (international auxiliary language association)" },
  { code: "ik", label: "Inupiaq", flag: "🌐", canonical: "inupiaq" },
  { code: "os", label: "Iron Ossetic", flag: "🌐", canonical: "iron ossetic" },
  { code: "its", label: "Isekiri", flag: "🌐", canonical: "isekiri" },
  { code: "iso", label: "Isoko", flag: "🌐", canonical: "isoko" },
  { code: "itw", label: "Ito", flag: "🌐", canonical: "ito" },
  { code: "itz", label: "Itzá", flag: "🌐", canonical: "itzá" },
  { code: "vmj", label: "Ixtayutla Mixtec", flag: "🌐", canonical: "ixtayutla mixtec" },
  { code: "ijc", label: "Izon", flag: "🌐", canonical: "izon" },
  { code: "jax", label: "Jambi Malay", flag: "🌐", canonical: "jambi malay" },
  { code: "jqr", label: "Jaqaru", flag: "🌐", canonical: "jaqaru" },
  { code: "qxw", label: "Jauja Wanca Quechua", flag: "🌐", canonical: "jauja wanca quechua" },
  { code: "jns", label: "Jaunsari", flag: "🌐", canonical: "jaunsari" },
  { code: "jv", label: "Javanese", flag: "🌐", canonical: "javanese" },
  { code: "juo", label: "Jiba", flag: "🌐", canonical: "jiba" },
  { code: "kaj", label: "Jju", flag: "🌐", canonical: "jju" },
  { code: "aju", label: "Judeo-Moroccan Arabic", flag: "🌐", canonical: "judeo-moroccan arabic" },
  { code: "vmc", label: "Juxtlahuaca Mixtec", flag: "🌐", canonical: "juxtlahuaca mixtec" },
  { code: "kbd", label: "Kabardian", flag: "🌐", canonical: "kabardian" },
  { code: "lkb", label: "Kabras", flag: "🌐", canonical: "kabras" },
  { code: "kea", label: "Kabuverdianu", flag: "🌐", canonical: "kabuverdianu" },
  { code: "kab", label: "Kabyle", flag: "🌐", canonical: "kabyle" },
  { code: "gjk", label: "Kachi Koli", flag: "🌐", canonical: "kachi koli" },
  { code: "ckr", label: "Kairak", flag: "🌐", canonical: "kairak" },
  { code: "ijn", label: "Kalabari", flag: "🌐", canonical: "kalabari" },
  { code: "kls", label: "Kalasha", flag: "🌐", canonical: "kalasha" },
  { code: "kln", label: "Kalenjin", flag: "🌐", canonical: "kalenjin" },
  { code: "xka", label: "Kalkoti", flag: "🌐", canonical: "kalkoti" },
  { code: "kam", label: "Kamba", flag: "🌐", canonical: "kamba" },
  { code: "kcq", label: "Kamo", flag: "🌐", canonical: "kamo" },
  { code: "bjj", label: "Kanauji", flag: "🌐", canonical: "kanauji" },
  { code: "kbl", label: "Kanembu", flag: "🌐", canonical: "kanembu" },
  { code: "kai", label: "Karekare", flag: "🌐", canonical: "karekare" },
  { code: "ks", label: "Kashmiri", flag: "🌐", canonical: "kashmiri" },
  { code: "tkt", label: "Kathoriya Tharu", flag: "🌐", canonical: "kathoriya tharu" },
  { code: "bsh", label: "Kati", flag: "🌐", canonical: "kati" },
  { code: "eyo", label: "Keiyo", flag: "🌐", canonical: "keiyo" },
  { code: "khg", label: "Khams Tibetan", flag: "🌐", canonical: "khams tibetan" },
  { code: "ogo", label: "Khana", flag: "🌐", canonical: "khana" },
  { code: "xhe", label: "Khetrani", flag: "🌐", canonical: "khetrani" },
  { code: "khw", label: "Khowar", flag: "🌐", canonical: "khowar" },
  { code: "zga", label: "Kinga", flag: "🌐", canonical: "kinga" },
  { code: "kfk", label: "Kinnauri", flag: "🌐", canonical: "kinnauri" },
  { code: "rw", label: "Kinyarwanda", flag: "🌐", canonical: "kinyarwanda" },
  { code: "ky", label: "Kirghiz", flag: "🌐", canonical: "kirghiz" },
  { code: "fkk", label: "Kirya-Konzəl", flag: "🌐", canonical: "kirya-konzəl" },
  { code: "thq", label: "Kochila Tharu", flag: "🌐", canonical: "kochila tharu" },
  { code: "plk", label: "Kohistani Shina", flag: "🌐", canonical: "kohistani shina" },
  { code: "bcs", label: "Kohumono", flag: "🌐", canonical: "kohumono" },
  { code: "trp", label: "Kok Borok", flag: "🌐", canonical: "kok borok" },
  { code: "kol", label: "Kol (Papua New Guinea)", flag: "🌐", canonical: "kol (papua new guinea)" },
  { code: "bkm", label: "Kom (Cameroon)", flag: "🌐", canonical: "kom (cameroon)" },
  { code: "kmy", label: "Koma", flag: "🌐", canonical: "koma" },
  { code: "knn", label: "Konkani", flag: "🌐", canonical: "konkani" },
  { code: "koo", label: "Konzo", flag: "🌐", canonical: "konzo" },
  { code: "kfp", label: "Korwa", flag: "🌐", canonical: "korwa" },
  { code: "kfe", label: "Kota (India)", flag: "🌐", canonical: "kota (india)" },
  { code: "eko", label: "Koti", flag: "🌐", canonical: "koti" },
  { code: "ksd", label: "Kuanua", flag: "🌐", canonical: "kuanua" },
  { code: "kj", label: "Kuanyama", flag: "🌐", canonical: "kuanyama" },
  { code: "uki", label: "Kui (India)", flag: "🌐", canonical: "kui (india)" },
  { code: "bbu", label: "Kulung (Nigeria)", flag: "🌐", canonical: "kulung (nigeria)" },
  { code: "kto", label: "Kuot", flag: "🌐", canonical: "kuot" },
  { code: "kuh", label: "Kushi", flag: "🌐", canonical: "kushi" },
  { code: "kwm", label: "Kwambi", flag: "🌐", canonical: "kwambi" },
  { code: "nmg", label: "Kwasio", flag: "🌐", canonical: "kwasio" },
  { code: "lla", label: "Lala-Roba", flag: "🌐", canonical: "lala-roba" },
  { code: "hia", label: "Lamang", flag: "🌐", canonical: "lamang" },
  { code: "alo", label: "Larike-Wakasihu", flag: "🌐", canonical: "larike-wakasihu" },
  { code: "lss", label: "Lasi", flag: "🌐", canonical: "lasi" },
  { code: "ltg", label: "Latgalian", flag: "🌐", canonical: "latgalian" },
  { code: "apc", label: "Levantine Arabic", flag: "🌐", canonical: "levantine arabic" },
  { code: "ste", label: "Liana-Seti", flag: "🌐", canonical: "liana-seti" },
  { code: "xpe", label: "Liberia Kpelle", flag: "🌐", canonical: "liberia kpelle" },
  { code: "lir", label: "Liberian English", flag: "🌐", canonical: "liberian english" },
  { code: "ayl", label: "Libyan Arabic", flag: "🌐", canonical: "libyan arabic" },
  { code: "lij", label: "Ligurian", flag: "🌐", canonical: "ligurian" },
  { code: "mgi", label: "Lijili", flag: "🌐", canonical: "lijili" },
  { code: "ln", label: "Lingala", flag: "🌐", canonical: "lingala" },
  { code: "lrk", label: "Loarki", flag: "🌐", canonical: "loarki" },
  { code: "rag", label: "Logooli", flag: "🌐", canonical: "logooli" },
  { code: "src", label: "Logudorese Sardinian", flag: "🌐", canonical: "logudorese sardinian" },
  { code: "qvj", label: "Loja Highland Quichua", flag: "🌐", canonical: "loja highland quichua" },
  { code: "loa", label: "Loloda", flag: "🌐", canonical: "loloda" },
  { code: "lnu", label: "Longuda", flag: "🌐", canonical: "longuda" },
  { code: "ztp", label: "Loxicha Zapotec", flag: "🌐", canonical: "loxicha zapotec" },
  { code: "lua", label: "Luba-Lulua", flag: "🌐", canonical: "luba-lulua" },
  { code: "luo", label: "Luo", flag: "🌐", canonical: "luo" },
  { code: "lus", label: "Lushai", flag: "🌐", canonical: "lushai" },
  { code: "lb", label: "Luxembourgish", flag: "🌐", canonical: "luxembourgish" },
  { code: "ffm", label: "Maasina Fulfulde", flag: "🌐", canonical: "maasina fulfulde" },
  { code: "mde", label: "Maba (Chad)", flag: "🌐", canonical: "maba (chad)" },
  { code: "rup", label: "Macedo-Romanian", flag: "🌐", canonical: "macedo-romanian" },
  { code: "mxu", label: "Mada (Cameroon)", flag: "🌐", canonical: "mada (cameroon)" },
  { code: "maf", label: "Mafa", flag: "🌐", canonical: "mafa" },
  { code: "mai", label: "Maithili", flag: "🌐", canonical: "maithili" },
  { code: "gcc", label: "Mali", flag: "🌐", canonical: "mali" },
  { code: "tcf", label: "Malinaltepec Me'phaa", flag: "🌐", canonical: "malinaltepec me'phaa" },
  { code: "mt", label: "Maltese", flag: "🌐", canonical: "maltese" },
  { code: "tbf", label: "Mandara", flag: "🌐", canonical: "mandara" },
  { code: "mfv", label: "Mandjak", flag: "🌐", canonical: "mandjak" },
  { code: "mqy", label: "Manggarai", flag: "🌐", canonical: "manggarai" },
  { code: "mni", label: "Manipuri", flag: "🌐", canonical: "manipuri" },
  { code: "msw", label: "Mansoanka", flag: "🌐", canonical: "mansoanka" },
  { code: "gv", label: "Manx", flag: "🌐", canonical: "manx" },
  { code: "mi", label: "Maori", flag: "🌐", canonical: "maori" },
  { code: "mrt", label: "Marghi Central", flag: "🌐", canonical: "marghi central" },
  { code: "mfm", label: "Marghi South", flag: "🌐", canonical: "marghi south" },
  { code: "mrr", label: "Maria (India)", flag: "🌐", canonical: "maria (india)" },
  { code: "mve", label: "Marwari (Pakistan)", flag: "🌐", canonical: "marwari (pakistan)" },
  { code: "mcn", label: "Masana", flag: "🌐", canonical: "masana" },
  { code: "msh", label: "Masikoro Malagasy", flag: "🌐", canonical: "masikoro malagasy" },
  { code: "mcf", label: "Matsés", flag: "🌐", canonical: "matsés" },
  { code: "zpy", label: "Mazaltepec Zapotec", flag: "🌐", canonical: "mazaltepec zapotec" },
  { code: "vmz", label: "Mazatlán Mazatec", flag: "🌐", canonical: "mazatlán mazatec" },
  { code: "mzl", label: "Mazatlán Mixe", flag: "🌐", canonical: "mazatlán mixe" },
  { code: "mfo", label: "Mbe", flag: "🌐", canonical: "mbe" },
  { code: "mbo", label: "Mbo (Cameroon)", flag: "🌐", canonical: "mbo (cameroon)" },
  { code: "mdd", label: "Mbum", flag: "🌐", canonical: "mbum" },
  { code: "byv", label: "Medumba", flag: "🌐", canonical: "medumba" },
  { code: "mek", label: "Mekeo", flag: "🌐", canonical: "mekeo" },
  { code: "mer", label: "Meru", flag: "🌐", canonical: "meru" },
  { code: "acm", label: "Mesopotamian Arabic", flag: "🌐", canonical: "mesopotamian arabic" },
  { code: "mtr", label: "Mewari", flag: "🌐", canonical: "mewari" },
  { code: "nan", label: "Min Nan Chinese", flag: "🌐", canonical: "min nan chinese" },
  { code: "xmf", label: "Mingrelian", flag: "🌐", canonical: "mingrelian" },
  { code: "vmm", label: "Mitlatongo Mixtec", flag: "🌐", canonical: "mitlatongo mixtec" },
  { code: "mkf", label: "Miya", flag: "🌐", canonical: "miya" },
  { code: "bri", label: "Mokpwe", flag: "🌐", canonical: "mokpwe" },
  { code: "mdf", label: "Moksha", flag: "🌐", canonical: "moksha" },
  { code: "ver", label: "Mom Jango", flag: "🌐", canonical: "mom jango" },
  { code: "ary", label: "Moroccan Arabic", flag: "🌐", canonical: "moroccan arabic" },
  { code: "meu", label: "Motu", flag: "🌐", canonical: "motu" },
  { code: "mcx", label: "Mpiemo", flag: "🌐", canonical: "mpiemo" },
  { code: "mgg", label: "Mpumpong", flag: "🌐", canonical: "mpumpong" },
  { code: "mua", label: "Mundang", flag: "🌐", canonical: "mundang" },
  { code: "mhk", label: "Mungaka", flag: "🌐", canonical: "mungaka" },
  { code: "mse", label: "Musey", flag: "🌐", canonical: "musey" },
  { code: "mug", label: "Musgu", flag: "🌐", canonical: "musgu" },
  { code: "mui", label: "Musi", flag: "🌐", canonical: "musi" },
  { code: "mne", label: "Naba", flag: "🌐", canonical: "naba" },
  { code: "ars", label: "Najdi Arabic", flag: "🌐", canonical: "najdi arabic" },
  { code: "nal", label: "Nalik", flag: "🌐", canonical: "nalik" },
  { code: "nmz", label: "Nawdm", flag: "🌐", canonical: "nawdm" },
  { code: "ng", label: "Ndonga", flag: "🌐", canonical: "ndonga" },
  { code: "nap", label: "Neapolitan", flag: "🌐", canonical: "neapolitan" },
  { code: "npi", label: "Nepali", flag: "🌐", canonical: "nepali" },
  { code: "nbh", label: "Ngamo", flag: "🌐", canonical: "ngamo" },
  { code: "anc", label: "Ngas", flag: "🌐", canonical: "ngas" },
  { code: "nnh", label: "Ngiemboon", flag: "🌐", canonical: "ngiemboon" },
  { code: "ngi", label: "Ngizim", flag: "🌐", canonical: "ngizim" },
  { code: "jgo", label: "Ngomba", flag: "🌐", canonical: "ngomba" },
  { code: "nla", label: "Ngombale", flag: "🌐", canonical: "ngombale" },
  { code: "fuv", label: "Nigerian Fulfulde", flag: "🌐", canonical: "nigerian fulfulde" },
  { code: "pcm", label: "Nigerian Pidgin", flag: "🌐", canonical: "nigerian pidgin" },
  { code: "noe", label: "Nimadi", flag: "🌐", canonical: "nimadi" },
  { code: "fia", label: "Nobiin", flag: "🌐", canonical: "nobiin" },
  { code: "ayp", label: "North Mesopotamian Arabic", flag: "🌐", canonical: "north mesopotamian arabic" },
  { code: "max", label: "North Moluccan Malay", flag: "🌐", canonical: "north moluccan malay" },
  { code: "bmm", label: "Northern Betsimisaraka Malagasy", flag: "🌐", canonical: "northern betsimisaraka malagasy" },
  { code: "hno", label: "Northern Hindko", flag: "🌐", canonical: "northern hindko" },
  { code: "kmr", label: "Northern Kurdish", flag: "🌐", canonical: "northern kurdish" },
  { code: "pmq", label: "Northern Pame", flag: "🌐", canonical: "northern pame" },
  { code: "pbu", label: "Northern Pashto", flag: "🌐", canonical: "northern pashto" },
  { code: "uzn", label: "Northern Uzbek", flag: "🌐", canonical: "northern uzbek" },
  { code: "gya", label: "Northwest Gbaya", flag: "🌐", canonical: "northwest gbaya" },
  { code: "nb", label: "Norwegian Bokmål", flag: "🌐", canonical: "norwegian bokmål" },
  { code: "nn", label: "Norwegian Nynorsk", flag: "🌐", canonical: "norwegian nynorsk" },
  { code: "ncf", label: "Notsi", flag: "🌐", canonical: "notsi" },
  { code: "yes", label: "Nyankpa", flag: "🌐", canonical: "nyankpa" },
  { code: "nyu", label: "Nyungwe", flag: "🌐", canonical: "nyungwe" },
  { code: "nja", label: "Nzanyi", flag: "🌐", canonical: "nzanyi" },
  { code: "hux", label: "Nüpode Huitoto", flag: "🌐", canonical: "nüpode huitoto" },
  { code: "oc", label: "Occitan", flag: "🌐", canonical: "occitan" },
  { code: "odk", label: "Od", flag: "🌐", canonical: "od" },
  { code: "ory", label: "Odia", flag: "🌐", canonical: "odia" },
  { code: "odu", label: "Odual", flag: "🌐", canonical: "odual" },
  { code: "acx", label: "Omani Arabic", flag: "🌐", canonical: "omani arabic" },
  { code: "nlv", label: "Orizaba Nahuatl", flag: "🌐", canonical: "orizaba nahuatl" },
  { code: "orc", label: "Orma", flag: "🌐", canonical: "orma" },
  { code: "oru", label: "Ormuri", flag: "🌐", canonical: "ormuri" },
  { code: "om", label: "Oromo", flag: "🌐", canonical: "oromo" },
  { code: "phr", label: "Pahari-Potwari", flag: "🌐", canonical: "pahari-potwari" },
  { code: "pwn", label: "Paiwan", flag: "🌐", canonical: "paiwan" },
  { code: "pmy", label: "Papuan Malay", flag: "🌐", canonical: "papuan malay" },
  { code: "kvx", label: "Parkari Koli", flag: "🌐", canonical: "parkari koli" },
  { code: "nso", label: "Pedi", flag: "🌐", canonical: "pedi" },
  { code: "pip", label: "Pero", flag: "🌐", canonical: "pero" },
  { code: "pex", label: "Petats", flag: "🌐", canonical: "petats" },
  { code: "phl", label: "Phalura", flag: "🌐", canonical: "phalura" },
  { code: "pms", label: "Piemontese", flag: "🌐", canonical: "piemontese" },
  { code: "piy", label: "Piya-Kwonci", flag: "🌐", canonical: "piya-kwonci" },
  { code: "plt", label: "Plateau Malagasy", flag: "🌐", canonical: "plateau malagasy" },
  { code: "poc", label: "Poqomam", flag: "🌐", canonical: "poqomam" },
  { code: "fuc", label: "Pulaar", flag: "🌐", canonical: "pulaar" },
  { code: "fuf", label: "Pular", flag: "🌐", canonical: "pular" },
  { code: "qxp", label: "Puno Quechua", flag: "🌐", canonical: "puno quechua" },
  { code: "ps", label: "Pushto", flag: "🌐", canonical: "pushto" },
  { code: "pko", label: "Pökoot", flag: "🌐", canonical: "pökoot" },
  { code: "byx", label: "Qaqet", flag: "🌐", canonical: "qaqet" },
  { code: "chq", label: "Quiotepec Chinantec", flag: "🌐", canonical: "quiotepec chinantec" },
  { code: "thr", label: "Rana Tharu", flag: "🌐", canonical: "rana tharu" },
  { code: "lag", label: "Rangi", flag: "🌐", canonical: "rangi" },
  { code: "kyx", label: "Rapoisi", flag: "🌐", canonical: "rapoisi" },
  { code: "rth", label: "Ratahan", flag: "🌐", canonical: "ratahan" },
  { code: "zor", label: "Rayón Zoque", flag: "🌐", canonical: "rayón zoque" },
  { code: "rm", label: "Romansh", flag: "🌐", canonical: "romansh" },
  { code: "rof", label: "Rombo", flag: "🌐", canonical: "rombo" },
  { code: "roo", label: "Rotokas", flag: "🌐", canonical: "rotokas" },
  { code: "dru", label: "Rukai", flag: "🌐", canonical: "rukai" },
  { code: "quv", label: "Sacapulteco", flag: "🌐", canonical: "sacapulteco" },
  { code: "aec", label: "Saidi Arabic", flag: "🌐", canonical: "saidi arabic" },
  { code: "skg", label: "Sakalava Malagasy", flag: "🌐", canonical: "sakalava malagasy" },
  { code: "szy", label: "Sakizaya", flag: "🌐", canonical: "sakizaya" },
  { code: "sau", label: "Saleman", flag: "🌐", canonical: "saleman" },
  { code: "ccg", label: "Samba Daka", flag: "🌐", canonical: "samba daka" },
  { code: "ndi", label: "Samba Leko", flag: "🌐", canonical: "samba leko" },
  { code: "pow", label: "San Felipe Otlaltepec Popoloca", flag: "🌐", canonical: "san felipe otlaltepec popoloca" },
  { code: "hue", label: "San Francisco Del Mar Huave", flag: "🌐", canonical: "san francisco del mar huave" },
  { code: "poe", label: "San Juan Atzingo Popoloca", flag: "🌐", canonical: "san juan atzingo popoloca" },
  { code: "trq", label: "San Martín Itunyoso Triqui", flag: "🌐", canonical: "san martín itunyoso triqui" },
  { code: "mig", label: "San Miguel El Grande Mixtec", flag: "🌐", canonical: "san miguel el grande mixtec" },
  { code: "ssi", label: "Sansi", flag: "🌐", canonical: "sansi" },
  { code: "sa", label: "Sanskrit", flag: "🌐", canonical: "sanskrit" },
  { code: "qxt", label: "Santa Ana de Tusi Pasco Quechua", flag: "🌐", canonical: "santa ana de tusi pasco quechua" },
  { code: "ztn", label: "Santa Catarina Albarradas Zapotec", flag: "🌐", canonical: "santa catarina albarradas zapotec" },
  { code: "sat", label: "Santali", flag: "🌐", canonical: "santali" },
  { code: "qus", label: "Santiago del Estero Quichua", flag: "🌐", canonical: "santiago del estero quichua" },
  { code: "sps", label: "Saposa", flag: "🌐", canonical: "saposa" },
  { code: "skr", label: "Saraiki", flag: "🌐", canonical: "saraiki" },
  { code: "sc", label: "Sardinian", flag: "🌐", canonical: "sardinian" },
  { code: "say", label: "Saya", flag: "🌐", canonical: "saya" },
  { code: "trv", label: "Sediq", flag: "🌐", canonical: "sediq" },
  { code: "sei", label: "Seri", flag: "🌐", canonical: "seri" },
  { code: "scl", label: "Shina", flag: "🌐", canonical: "shina" },
  { code: "sn", label: "Shona", flag: "🌐", canonical: "shona" },
  { code: "sjr", label: "Siar-Lak", flag: "🌐", canonical: "siar-lak" },
  { code: "nco", label: "Sibe", flag: "🌐", canonical: "sibe" },
  { code: "scn", label: "Sicilian", flag: "🌐", canonical: "sicilian" },
  { code: "qws", label: "Sihuas Ancash Quechua", flag: "🌐", canonical: "sihuas ancash quechua" },
  { code: "sip", label: "Sikkimese", flag: "🌐", canonical: "sikkimese" },
  { code: "snc", label: "Sinaugoro", flag: "🌐", canonical: "sinaugoro" },
  { code: "sd", label: "Sindhi", flag: "🌐", canonical: "sindhi" },
  { code: "sbn", label: "Sindhi Bhil", flag: "🌐", canonical: "sindhi bhil" },
  { code: "xti", label: "Sinicahua Mixtec", flag: "🌐", canonical: "sinicahua mixtec" },
  { code: "qum", label: "Sipacapense", flag: "🌐", canonical: "sipacapense" },
  { code: "siw", label: "Siwai", flag: "🌐", canonical: "siwai" },
  { code: "sol", label: "Solos", flag: "🌐", canonical: "solos" },
  { code: "snk", label: "Soninke", flag: "🌐", canonical: "soninke" },
  { code: "giz", label: "South Giziga", flag: "🌐", canonical: "south giziga" },
  { code: "cpy", label: "South Ucayali Ashéninka", flag: "🌐", canonical: "south ucayali ashéninka" },
  { code: "mxy", label: "Southeastern Nochixtlán Mixtec", flag: "🌐", canonical: "southeastern nochixtlán mixtec" },
  { code: "bzc", label: "Southern Betsimisaraka Malagasy", flag: "🌐", canonical: "southern betsimisaraka malagasy" },
  { code: "pbt", label: "Southern Pashto", flag: "🌐", canonical: "southern pashto" },
  { code: "qup", label: "Southern Pastaza Quechua", flag: "🌐", canonical: "southern pastaza quechua" },
  { code: "vmp", label: "Soyaltepec Mazatec", flag: "🌐", canonical: "soyaltepec mazatec" },
  { code: "zgh", label: "Standard Moroccan Tamazight", flag: "🌐", canonical: "standard moroccan tamazight" },
  { code: "apd", label: "Sudanese Arabic", flag: "🌐", canonical: "sudanese arabic" },
  { code: "sua", label: "Sulka", flag: "🌐", canonical: "sulka" },
  { code: "sva", label: "Svan", flag: "🌐", canonical: "svan" },
  { code: "rob", label: "Tae'", flag: "🌐", canonical: "tae'" },
  { code: "thv", label: "Tahaggart Tamahaq", flag: "🌐", canonical: "tahaggart tamahaq" },
  { code: "dav", label: "Taita", flag: "🌐", canonical: "taita" },
  { code: "tg", label: "Tajik", flag: "🌐", canonical: "tajik" },
  { code: "tdx", label: "Tandroy-Mahafaly Malagasy", flag: "🌐", canonical: "tandroy-mahafaly malagasy" },
  { code: "tan", label: "Tangale", flag: "🌐", canonical: "tangale" },
  { code: "txy", label: "Tanosy Malagasy", flag: "🌐", canonical: "tanosy malagasy" },
  { code: "yer", label: "Tarok", flag: "🌐", canonical: "tarok" },
  { code: "tt", label: "Tatar", flag: "🌐", canonical: "tatar" },
  { code: "tuq", label: "Tedaga", flag: "🌐", canonical: "tedaga" },
  { code: "kdh", label: "Tem", flag: "🌐", canonical: "tem" },
  { code: "tio", label: "Teop", flag: "🌐", canonical: "teop" },
  { code: "cux", label: "Tepeuxila Cuicatec", flag: "🌐", canonical: "tepeuxila cuicatec" },
  { code: "cte", label: "Tepinapa Chinantec", flag: "🌐", canonical: "tepinapa chinantec" },
  { code: "ttr", label: "Tera", flag: "🌐", canonical: "tera" },
  { code: "buo", label: "Terei", flag: "🌐", canonical: "terei" },
  { code: "twu", label: "Termanu", flag: "🌐", canonical: "termanu" },
  { code: "tkg", label: "Tesaka Malagasy", flag: "🌐", canonical: "tesaka malagasy" },
  { code: "nhg", label: "Tetelcingo Nahuatl", flag: "🌐", canonical: "tetelcingo nahuatl" },
  { code: "cut", label: "Teutila Cuicatec", flag: "🌐", canonical: "teutila cuicatec" },
  { code: "bo", label: "Tibetan", flag: "🌐", canonical: "tibetan" },
  { code: "mtx", label: "Tidaá Mixtec", flag: "🌐", canonical: "tidaá mixtec" },
  { code: "tvo", label: "Tidore", flag: "🌐", canonical: "tidore" },
  { code: "tgc", label: "Tigak", flag: "🌐", canonical: "tigak" },
  { code: "tig", label: "Tigre", flag: "🌐", canonical: "tigre" },
  { code: "ti", label: "Tigrinya", flag: "🌐", canonical: "tigrinya" },
  { code: "zts", label: "Tilquiapan Zapotec", flag: "🌐", canonical: "tilquiapan zapotec" },
  { code: "tpz", label: "Tinputz", flag: "🌐", canonical: "tinputz" },
  { code: "tpl", label: "Tlacoapa Me'phaa", flag: "🌐", canonical: "tlacoapa me'phaa" },
  { code: "ctl", label: "Tlacoatzintepec Chinantec", flag: "🌐", canonical: "tlacoatzintepec chinantec" },
  { code: "tli", label: "Tlingit", flag: "🌐", canonical: "tlingit" },
  { code: "tok", label: "Toki Pona", flag: "🌐", canonical: "toki pona" },
  { code: "tqp", label: "Tomoip", flag: "🌐", canonical: "tomoip" },
  { code: "tdn", label: "Tondano", flag: "🌐", canonical: "tondano" },
  { code: "txs", label: "Tonsea", flag: "🌐", canonical: "tonsea" },
  { code: "ttj", label: "Tooro", flag: "🌐", canonical: "tooro" },
  { code: "ttu", label: "Torau", flag: "🌐", canonical: "torau" },
  { code: "trw", label: "Torwali", flag: "🌐", canonical: "torwali" },
  { code: "xmw", label: "Tsimihety Malagasy", flag: "🌐", canonical: "tsimihety malagasy" },
  { code: "lto", label: "Tsotso", flag: "🌐", canonical: "tsotso" },
  { code: "tn", label: "Tswana", flag: "🌐", canonical: "tswana" },
  { code: "tuy", label: "Tugen", flag: "🌐", canonical: "tugen" },
  { code: "bag", label: "Tuki", flag: "🌐", canonical: "tuki" },
  { code: "tul", label: "Tula", flag: "🌐", canonical: "tula" },
  { code: "tcy", label: "Tulu", flag: "🌐", canonical: "tulu" },
  { code: "tvu", label: "Tunen", flag: "🌐", canonical: "tunen" },
  { code: "lcm", label: "Tungag", flag: "🌐", canonical: "tungag" },
  { code: "aeb", label: "Tunisian Arabic", flag: "🌐", canonical: "tunisian arabic" },
  { code: "tui", label: "Tupuri", flag: "🌐", canonical: "tupuri" },
  { code: "tuv", label: "Turkana", flag: "🌐", canonical: "turkana" },
  { code: "tk", label: "Turkmen", flag: "🌐", canonical: "turkmen" },
  { code: "mtu", label: "Tututepec Mixtec", flag: "🌐", canonical: "tututepec mixtec" },
  { code: "tw", label: "Twi", flag: "🌐", canonical: "twi" },
  { code: "byc", label: "Ubaghara", flag: "🌐", canonical: "ubaghara" },
  { code: "ug", label: "Uighur", flag: "🌐", canonical: "uighur" },
  { code: "umb", label: "Umbundu", flag: "🌐", canonical: "umbundu" },
  { code: "hsb", label: "Upper Sorbian", flag: "🌐", canonical: "upper sorbian" },
  { code: "ush", label: "Ushojo", flag: "🌐", canonical: "ushojo" },
  { code: "vai", label: "Vai", flag: "🌐", canonical: "vai" },
  { code: "vot", label: "Votic", flag: "🌐", canonical: "votic" },
  { code: "vro", label: "Võro", flag: "🌐", canonical: "võro" },
  { code: "wci", label: "Waci Gbe", flag: "🌐", canonical: "waci gbe" },
  { code: "kxp", label: "Wadiyara Koli", flag: "🌐", canonical: "wadiyara koli" },
  { code: "wja", label: "Waja", flag: "🌐", canonical: "waja" },
  { code: "wbl", label: "Wakhi", flag: "🌐", canonical: "wakhi" },
  { code: "lwg", label: "Wanga", flag: "🌐", canonical: "wanga" },
  { code: "juk", label: "Wapan", flag: "🌐", canonical: "wapan" },
  { code: "wji", label: "Warji", flag: "🌐", canonical: "warji" },
  { code: "weo", label: "Wemale", flag: "🌐", canonical: "wemale" },
  { code: "fy", label: "Western Frisian", flag: "🌐", canonical: "western frisian" },
  { code: "pua", label: "Western Highland Purepecha", flag: "🌐", canonical: "western highland purepecha" },
  { code: "jmx", label: "Western Juxtlahuaca Mixtec", flag: "🌐", canonical: "western juxtlahuaca mixtec" },
  { code: "mlq", label: "Western Maninkakan", flag: "🌐", canonical: "western maninkakan" },
  { code: "mrj", label: "Western Mari", flag: "🌐", canonical: "western mari" },
  { code: "fuh", label: "Western Niger Fulfulde", flag: "🌐", canonical: "western niger fulfulde" },
  { code: "pnb", label: "Western Panjabi", flag: "🌐", canonical: "western panjabi" },
  { code: "wo", label: "Wolof", flag: "🌐", canonical: "wolof" },
  { code: "udl", label: "Wuzlam", flag: "🌐", canonical: "wuzlam" },
  { code: "ztg", label: "Xanaguía Zapotec", flag: "🌐", canonical: "xanaguía zapotec" },
  { code: "ekr", label: "Yace", flag: "🌐", canonical: "yace" },
  { code: "sah", label: "Yakut", flag: "🌐", canonical: "yakut" },
  { code: "jal", label: "Yalahatan", flag: "🌐", canonical: "yalahatan" },
  { code: "qur", label: "Yanahuanca Pasco Quechua", flag: "🌐", canonical: "yanahuanca pasco quechua" },
  { code: "yav", label: "Yangben", flag: "🌐", canonical: "yangben" },
  { code: "yaq", label: "Yaqui", flag: "🌐", canonical: "yaqui" },
  { code: "qux", label: "Yauyos Quechua", flag: "🌐", canonical: "yauyos quechua" },
  { code: "ets", label: "Yekhee", flag: "🌐", canonical: "yekhee" },
  { code: "yi", label: "Yiddish", flag: "🌐", canonical: "yiddish" },
  { code: "ydg", label: "Yidgha", flag: "🌐", canonical: "yidgha" },
  { code: "mab", label: "Yutanduchi Mixtec", flag: "🌐", canonical: "yutanduchi mixtec" },
  { code: "nhi", label: "Zacatlán-Ahuacatlán-Tepetzintla Nahuatl", flag: "🌐", canonical: "zacatlán-ahuacatlán-tepetzintla nahuatl" },
  { code: "dje", label: "Zarma", flag: "🌐", canonical: "zarma" },
  { code: "zza", label: "Zaza", flag: "🌐", canonical: "zaza" },
  { code: "aom", label: "Ömie", flag: "🌐", canonical: "ömie" },
];

export const LANGUAGE_COUNT = LANGUAGES.length;
